CREATE TABLE [dbo].[EMAIL] (
    [ID]           UNIQUEIDENTIFIER NOT NULL,
    [NOME]         NVARCHAR (150)   NOT NULL,
    [REMETENTE]    NVARCHAR (150)   NOT NULL,
    [DESTINATARIO] NVARCHAR (150)   NOT NULL,
    [DATAEMAIL]    DATETIME         NOT NULL,
    [CONTEUDO]     NVARCHAR (MAX)   NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);
